CREATE TABLE BOARD(
    NUM int,
    ID VARCHAR(50),
    TITLE VARCHAR(200),
    CONTENT VARCHAR(1000),
    WDATE DATE,
    PRIMARY KEY (NUM)
);

INSERT INTO BOARD(ID, TITLE, CONTENT, WDATE)
VALUES("person1", "제목", "hi.content", NOW());